import { Steps } from "./steps";

export const template4Steps: Steps = {
  1: {
    setting: "hero section's title",
    image: "./step-images/4/1.png",
    selector: "#hero-text",
    inputType: "text",
  },
  2: {
    setting: "hero section's description",
    image: "./step-images/4/2.png",
    selector: "#hero-description",
    inputType: "text",
  },
  3: {
    setting: "hero section's first button text",
    image: "./step-images/4/3.png",
    selector: "#hero-btn-1",
    inputType: "text",
  },
  4: {
    setting: "hero section's first button link",
    image: "./step-images/4/3.png",
    selector: "#hero-btn-1",
    inputType: "link",
  },
  5: {
    setting: "hero section's image",
    image: "./step-images/4/4.png",
    selector: "#hero-img",
    inputType: "image",
  },
  6: {
    setting: "top right button's text",
    image: "./step-images/4/5.png",
    selector: "#nav-btn",
    inputType: "text",
  },
  7: {
    setting: "top right button's link",
    image: "./step-images/4/5.png",
    selector: "#nav-btn",
    inputType: "link",
  },
  8: {
    setting: "website's logo",
    image: "./step-images/4/6.png",
    selector: "#logo",
    inputType: "image",
  },
  9: {
    setting: "first section's title",
    image: "./step-images/4/7.png",
    selector: "#first-title",
    inputType: "text",
  },
  10: {
    setting: "first section's description",
    image: "./step-images/4/23.png",
    selector: "#first-description",
    inputType: "text",
  },
  11: {
    setting: "first section's description",
    image: "./step-images/4/8.png",
    selector: "#second-sub-description",
    inputType: "text",
  },
  12: {
    setting: "first bullet point",
    image: "./step-images/4/9.png",
    selector: "#first-bullet-point",
    inputType: "text",
  },
  13: {
    setting: "second bullet point",
    image: "./step-images/4/10.png",
    selector: "#second-bullet-point",
    inputType: "text",
  },
  14: {
    setting: "third bullet point",
    image: "./step-images/4/11.png",
    selector: "#third-bullet-point",
    inputType: "text",
  },
  15: {
    setting: "second section's title",
    image: "./step-images/4/12.png",
    selector: "#second-title",
    inputType: "text",
  },
  16: {
    setting: "second section's description",
    image: "./step-images/4/13.png",
    selector: "#second-description",
    inputType: "text",
  },
  17: {
    setting: "first feature's title",
    image: "./step-images/4/14.png",
    selector: "#first-feature-title",
    inputType: "text",
  },
  18: {
    setting: "first feature's description",
    image: "./step-images/4/15.png",
    selector: "#first-feature-description",
    inputType: "text",
  },
  19: {
    setting: "second feature's title",
    image: "./step-images/4/16.png",
    selector: "#second-feature-title",
    inputType: "text",
  },
  20: {
    setting: "second feature's description",
    image: "./step-images/4/17.png",
    selector: "#second-feature-description",
    inputType: "text",
  },
  21: {
    setting: "third feature's title",
    image: "./step-images/4/18.png",
    selector: "#third-feature-title",
    inputType: "text",
  },
  22: {
    setting: "third feature's description",
    image: "./step-images/4/19.png",
    selector: "#third-feature-description",
    inputType: "text",
  },
  23: {
    setting: "footer's title",
    image: "./step-images/4/20.png",
    selector: "#footer-title",
    inputType: "text",
  },
  24: {
    setting: "footer's description",
    image: "./step-images/4/21.png",
    selector: "#footer-description",
    inputType: "text",
  },
  25: {
    setting: "footer's button text",
    image: "./step-images/4/22.png",
    selector: "#footer-btn",
    inputType: "text",
  },
  26: {
    setting: "footer's button link",
    image: "./step-images/4/22.png",
    selector: "#footer-btn",
    inputType: "link",
  },
  27: {
    setting: "website title",
    selector: "title",
    inputType: "text",
  },
};
