import { Steps } from "./steps";

export const template9Steps: Steps = {
  1: {
    setting: "hero section's title",
    image: "./step-images/9/1.png",
    selector: "#hero-text",
    inputType: "text",
  },
  2: {
    setting: "hero section's description",
    image: "./step-images/9/2.png",
    selector: "#hero-description",
    inputType: "text",
  },
  3: {
    setting: "hero section's first button's text",
    image: "./step-images/9/3.png",
    selector: "#hero-btn-1",
    inputType: "text",
  },
  4: {
    setting: "hero section's first button's link",
    image: "./step-images/9/3.png",
    selector: "#hero-btn-1",
    inputType: "link",
  },
  5: {
    setting: "hero section's second button's text",
    image: "./step-images/9/4.png",
    selector: "#hero-btn-2",
    inputType: "text",
  },
  6: {
    setting: "hero section's second button's link",
    image: "./step-images/9/4.png",
    selector: "#hero-btn-2",
    inputType: "link",
  },
  7: {
    setting: "hero section's image",
    image: "./step-images/9/5.png",
    selector: "#hero-img",
    inputType: "image",
  },
  8: {
    setting: "website's logo",
    image: "./step-images/9/6.png",
    selector: "#logo",
    inputType: "image",
  },
  9: {
    setting: "first feature's name",
    image: "./step-images/9/7.png",
    selector: "#feature1-name",
    inputType: "text",
  },
  10: {
    setting: "first feature's description",
    image: "./step-images/9/8.png",
    selector: "#feature1-description",
    inputType: "text",
  },
  11: {
    setting: "second feature's name",
    image: "./step-images/9/9.png",
    selector: "#feature2-name",
    inputType: "text",
  },
  12: {
    setting: "second feature's description",
    image: "./step-images/9/10.png",
    selector: "#feature2-description",
    inputType: "text",
  },
  13: {
    setting: "third feature's name",
    image: "./step-images/9/11.png",
    selector: "#feature3-name",
    inputType: "text",
  },
  14: {
    setting: "third feature's description",
    image: "./step-images/9/12.png",
    selector: "#feature3-description",
    inputType: "text",
  },
  15: {
    setting: "fourth feature's name",
    image: "./step-images/9/13.png",
    selector: "#feature4-name",
    inputType: "text",
  },
  16: {
    setting: "fourth feature's description",
    image: "./step-images/9/14.png",
    selector: "#feature4-description",
    inputType: "text",
  },
  17: {
    setting: "fifth feature's name",
    image: "./step-images/9/15.png",
    selector: "#feature5-name",
    inputType: "text",
  },
  18: {
    setting: "fifth feature's description",
    image: "./step-images/9/16.png",
    selector: "#feature5-description",
    inputType: "text",
  },
  19: {
    setting: "sixth feature's name",
    image: "./step-images/9/17.png",
    selector: "#feature6-name",
    inputType: "text",
  },
  20: {
    setting: "sixth feature's description",
    image: "./step-images/9/18.png",
    selector: "#feature6-description",
    inputType: "text",
  },
  21: {
    setting: "second section's title",
    image: "./step-images/9/19.png",
    selector: "#section2-title",
    inputType: "text",
  },
  22: {
    setting: "second section's description",
    image: "./step-images/9/20.png",
    selector: "#section2-description",
    inputType: "text",
  },
  23: {
    setting: "second section's button's text",
    image: "./step-images/9/21.png",
    selector: "#second-btn",
    inputType: "text",
  },
  24: {
    setting: "second section's button's link",
    image: "./step-images/9/21.png",
    selector: "#second-btn",
    inputType: "link",
  },
  25: {
    setting: "website title",
    selector: "title",
    inputType: "text",
  },
};
